import type { AppData } from "./types";

export const SAMPLE: AppData = {
  sites: [
    {
      id: "s-sahyadri",
      name: "Sahyadri Heights",
      nameMr: "सह्याद्री हाइट्स",
      location: "Baner, Pune",
      locationMr: "बाणेर, पुणे",
      client: "Sahyadri Developers",
      contractor: "Kulkarni Constructions",
      type: "Residential G+14",
      typeMr: "निवासी जी+१४",
      status: "active",
      startDate: "2025-06-12",
      targetDate: "2027-03-31",
      engineer: "R. Deshpande",
      image: "/sites/sahyadri.jpg",
      scope: "RCC frame, 112 flats, two basements",
      scopeMr: "RCC फ्रेम, ११२ फ्लॅट, दोन बेसमेंट",
    },
    {
      id: "s-godavari",
      name: "Godavari ROB",
      nameMr: "गोदावरी आरओबी",
      location: "Nashik–Peth road, Nashik",
      locationMr: "नाशिक–पेठ रस्ता, नाशिक",
      client: "PWD Maharashtra",
      contractor: "Deshmukh Infra",
      type: "Road over bridge",
      typeMr: "रोड ओव्हर ब्रिज",
      status: "delayed",
      startDate: "2025-11-04",
      targetDate: "2026-09-15",
      engineer: "S. Patil",
      image: "/sites/godavari.jpg",
      scope: "4-lane ROB, 8 spans, 32 piles",
      scopeMr: "४ लेन आरओबी, ८ स्पॅन, ३२ पाइल्स",
    },
    {
      id: "s-vidya",
      name: "Vidya Mandir",
      nameMr: "विद्या मंदिर",
      location: "Wardha Road, Nagpur",
      locationMr: "वर्धा रोड, नागपूर",
      client: "Zilla Parishad Nagpur",
      contractor: "Joshi Builders",
      type: "School, G+1",
      typeMr: "शाळा, जी+१",
      status: "finishing",
      startDate: "2025-02-18",
      targetDate: "2026-10-30",
      engineer: "A. Bhonsle",
      image: "/sites/vidya.jpg",
      scope: "12 classrooms, labs, assembly court",
      scopeMr: "१२ वर्गखोली, लॅब, सभा मैदान",
    },
  ],
  work: [
    { id: "w1", siteId: "s-sahyadri", name: "Excavation", nameMr: "खोदकाम", unit: "cum", planned: 2400, done: 2400 },
    { id: "w2", siteId: "s-sahyadri", name: "PCC", nameMr: "पीसीसी", unit: "cum", planned: 180, done: 180 },
    { id: "w3", siteId: "s-sahyadri", name: "Footings", nameMr: "फूटिंग", unit: "cum", planned: 420, done: 420 },
    { id: "w4", siteId: "s-sahyadri", name: "Columns", nameMr: "स्तंभ", unit: "cum", planned: 980, done: 710 },
    { id: "w5", siteId: "s-sahyadri", name: "Slabs", nameMr: "स्लॅब", unit: "floors", planned: 14, done: 8 },
    { id: "w6", siteId: "s-sahyadri", name: "Brickwork", nameMr: "विटकाम", unit: "sqm", planned: 8500, done: 3120 },
    { id: "w7", siteId: "s-sahyadri", name: "Internal plaster", nameMr: "आतील प्लास्टर", unit: "sqm", planned: 16000, done: 1840 },
    { id: "w8", siteId: "s-godavari", name: "Piling", nameMr: "पाइलिंग", unit: "nos", planned: 32, done: 24 },
    { id: "w9", siteId: "s-godavari", name: "Pile caps", nameMr: "पाइल कॅप", unit: "nos", planned: 16, done: 8 },
    { id: "w10", siteId: "s-godavari", name: "Piers", nameMr: "पियर", unit: "nos", planned: 16, done: 6 },
    { id: "w11", siteId: "s-godavari", name: "Girder launch", nameMr: "गर्डर लॉन्च", unit: "spans", planned: 8, done: 2 },
    { id: "w12", siteId: "s-godavari", name: "Deck slab", nameMr: "डेक स्लॅब", unit: "spans", planned: 8, done: 0 },
    { id: "w13", siteId: "s-vidya", name: "RCC frame", nameMr: "RCC फ्रेम", unit: "%", planned: 100, done: 100 },
    { id: "w14", siteId: "s-vidya", name: "Brickwork", nameMr: "विटकाम", unit: "sqm", planned: 2100, done: 1980 },
    { id: "w15", siteId: "s-vidya", name: "Plaster", nameMr: "प्लास्टर", unit: "sqm", planned: 4200, done: 3680 },
    { id: "w16", siteId: "s-vidya", name: "Flooring", nameMr: "फ्लोअरिंग", unit: "sqm", planned: 1800, done: 1260 },
    { id: "w17", siteId: "s-vidya", name: "Painting", nameMr: "रंगकाम", unit: "sqm", planned: 5200, done: 2080 },
    { id: "w18", siteId: "s-vidya", name: "MEP", nameMr: "MEP", unit: "%", planned: 100, done: 58 },
  ],
  materials: [
    { id: "m1", siteId: "s-sahyadri", name: "OPC 53 cement", nameMr: "OPC ५३ सिमेंट", unit: "bags", received: 4200, consumed: 3680, reorderAt: 400 },
    { id: "m2", siteId: "s-sahyadri", name: "TMT 500 16mm", nameMr: "TMT ५०० १६मिमी", unit: "MT", received: 86, consumed: 71, reorderAt: 8 },
    { id: "m3", siteId: "s-sahyadri", name: "TMT 500 12mm", nameMr: "TMT ५०० १२मिमी", unit: "MT", received: 54, consumed: 49, reorderAt: 6 },
    { id: "m4", siteId: "s-sahyadri", name: "20mm aggregate", nameMr: "२०मिमी मेटल", unit: "cum", received: 980, consumed: 740, reorderAt: 80 },
    { id: "m5", siteId: "s-sahyadri", name: "River sand", nameMr: "नदी वाळू", unit: "cum", received: 620, consumed: 590, reorderAt: 50 },
    { id: "m6", siteId: "s-sahyadri", name: "Fly ash bricks", nameMr: "फ्लाय अॅश विटा", unit: "nos", received: 180000, consumed: 124000, reorderAt: 20000 },
    { id: "m7", siteId: "s-godavari", name: "OPC 53 cement", nameMr: "OPC ५३ सिमेंट", unit: "bags", received: 2100, consumed: 1880, reorderAt: 250 },
    { id: "m8", siteId: "s-godavari", name: "TMT 500 32mm", nameMr: "TMT ५०० ३२मिमी", unit: "MT", received: 64, consumed: 41, reorderAt: 10 },
    { id: "m9", siteId: "s-godavari", name: "20mm aggregate", nameMr: "२०मिमी मेटल", unit: "cum", received: 1400, consumed: 920, reorderAt: 120 },
    { id: "m10", siteId: "s-godavari", name: "Shuttering ply", nameMr: "शटरिंग प्लाय", unit: "sheets", received: 240, consumed: 210, reorderAt: 40 },
    { id: "m11", siteId: "s-vidya", name: "OPC 53 cement", nameMr: "OPC ५३ सिमेंट", unit: "bags", received: 980, consumed: 910, reorderAt: 80 },
    { id: "m12", siteId: "s-vidya", name: "Vitrified tiles", nameMr: "व्हिट्रिफाइड टाइल्स", unit: "sqm", received: 1900, consumed: 1260, reorderAt: 200 },
    { id: "m13", siteId: "s-vidya", name: "Emulsion paint", nameMr: "इमल्शन पेंट", unit: "ltr", received: 820, consumed: 340, reorderAt: 80 },
  ],
  labor: [
    { id: "l1", siteId: "s-sahyadri", date: "2026-08-31", trade: "Mason", tradeMr: "गवंडी", present: 18, planned: 22 },
    { id: "l2", siteId: "s-sahyadri", date: "2026-08-31", trade: "Helper", tradeMr: "मदतनीस", present: 34, planned: 36 },
    { id: "l3", siteId: "s-sahyadri", date: "2026-08-31", trade: "Carpenter", tradeMr: "सुतार", present: 12, planned: 14 },
    { id: "l4", siteId: "s-sahyadri", date: "2026-08-31", trade: "Bar bender", tradeMr: "बार बेंडर", present: 9, planned: 10 },
    { id: "l5", siteId: "s-godavari", date: "2026-08-31", trade: "Mason", tradeMr: "गवंडी", present: 8, planned: 12 },
    { id: "l6", siteId: "s-godavari", date: "2026-08-31", trade: "Helper", tradeMr: "मदतनीस", present: 22, planned: 28 },
    { id: "l7", siteId: "s-godavari", date: "2026-08-31", trade: "Rigger", tradeMr: "रिगर", present: 6, planned: 8 },
    { id: "l8", siteId: "s-vidya", date: "2026-08-31", trade: "Mason", tradeMr: "गवंडी", present: 6, planned: 6 },
    { id: "l9", siteId: "s-vidya", date: "2026-08-31", trade: "Painter", tradeMr: "रंगारी", present: 11, planned: 14 },
    { id: "l10", siteId: "s-vidya", date: "2026-08-31", trade: "Electrician", tradeMr: "इलेक्ट्रीशियन", present: 4, planned: 4 },
    { id: "l11", siteId: "s-sahyadri", date: "2026-08-29", trade: "Mason", tradeMr: "गवंडी", present: 20, planned: 22 },
    { id: "l12", siteId: "s-sahyadri", date: "2026-08-29", trade: "Helper", tradeMr: "मदतनीस", present: 36, planned: 36 },
    { id: "l13", siteId: "s-godavari", date: "2026-08-29", trade: "Helper", tradeMr: "मदतनीस", present: 18, planned: 28 },
  ],
  dprs: [
    {
      id: "d1",
      siteId: "s-sahyadri",
      date: "2026-08-29",
      weather: "cloudy",
      workSummary: "Slab 8 shuttering 70% complete. Column C21–C28 casting done. Brickwork 4th floor east wing 18 sqm.",
      workSummaryMr: "स्लॅब ८ शटरिंग ७०% पूर्ण. स्तंभ C21–C28 कास्टिंग झाले. चौथा मजला पूर्व विंग विटकाम १८ चौ.मी.",
      laborCount: 71,
      delays: "Ready-mix delayed 90 minutes.",
      delaysMr: "रेडी मिक्स ९० मिनिटे उशीर.",
      remarks: "Night curing started on slab 7. Tower crane idle 2 hrs for rope inspection.",
      remarksMr: "स्लॅब ७ वर रात्री क्युरिंग सुरू. दोर तपासणीसाठी टॉवर क्रेन २ तास बंद.",
      engineer: "R. Deshpande",
      photos: ["/sites/sahyadri.jpg"],
    },
    {
      id: "d2",
      siteId: "s-godavari",
      date: "2026-08-29",
      weather: "rain",
      workSummary: "Pile P-25 and P-26 boring. Pile cap PC-4 reinforcement 40%. No girder movement.",
      workSummaryMr: "पाइल P-25 आणि P-26 बोरिंग. पाइल कॅप PC-4 स्टील ४०%. गर्डर हालचाल नाही.",
      laborCount: 36,
      delays: "Rain stoppage 3.5 hours after 14:00. Riverbed access muddy.",
      delaysMr: "दुपारी २ नंतर पावसामुळे ३.५ तास बंद. नदीपात्रात चिखल.",
      remarks: "Dewatering pumps on standby. Requested extra bog mats from store.",
      remarksMr: "डिवॉटरिंग पंप तयार. स्टोअरकडून अतिरिक्त बॉग मॅट मागितल्या.",
      engineer: "S. Patil",
      photos: ["/sites/godavari.jpg"],
    },
    {
      id: "d3",
      siteId: "s-vidya",
      date: "2026-08-29",
      weather: "clear",
      workSummary: "Corridor vitrified flooring 86 sqm. First-coat emulsion in classrooms 3–6. Electrical DB wiring lab block.",
      workSummaryMr: "कॉरिडॉर व्हिट्रिफाइड फ्लोअरिंग ८६ चौ.मी. वर्ग ३–६ मध्ये पहिला कोट इमल्शन. लॅब ब्लॉक विद्युत DB वायरिंग.",
      laborCount: 21,
      delays: "None.",
      delaysMr: "नाही.",
      remarks: "Tile shade lot 2 matches sample. Client visit scheduled Tuesday.",
      remarksMr: "टाइल शेड लॉट २ सॅम्पलशी जुळते. मंगळवारी क्लायंट भेट.",
      engineer: "A. Bhonsle",
      photos: ["/sites/vidya.jpg"],
    },
    {
      id: "d4",
      siteId: "s-sahyadri",
      date: "2026-08-28",
      weather: "hot",
      workSummary: "Column C12–C20 shuttering and steel. Slab 7 curing day 3. Staircase flight 6 risers cast.",
      workSummaryMr: "स्तंभ C12–C20 शटरिंग आणि स्टील. स्लॅब ७ क्युरिंग दिवस ३. जिना फ्लाइट ६ रायझर्स कास्ट.",
      laborCount: 68,
      delays: "None.",
      delaysMr: "नाही.",
      remarks: "Cover blocks short — 400 nos indented from Baner yard.",
      remarksMr: "कव्हर ब्लॉक्स कमी — बाणेर यार्डमधून ४०० नग मागवले.",
      engineer: "R. Deshpande",
      photos: [],
    },
    {
      id: "d5",
      siteId: "s-godavari",
      date: "2026-08-28",
      weather: "cloudy",
      workSummary: "Pier P3 shutter oiling. Pile P-24 concrete 18 cum. Approach embankment dressing 40 m.",
      workSummaryMr: "पियर P3 शटर ऑइलिंग. पाइल P-24 काँक्रीट १८ घनमी. अप्रोच एम्बँकमेंट ४० मी.",
      laborCount: 44,
      delays: "Waiting on 32mm TMT cut lengths from mill.",
      delaysMr: "मिलकडून ३२मिमी TMT कट लेंथची वाट.",
      remarks: "PWD AE visited. Asked for pile load test programme by Friday.",
      remarksMr: "PWD AE भेट. शुक्रवारपर्यंत पाइल लोड टेस्ट कार्यक्रम मागितला.",
      engineer: "S. Patil",
      photos: [],
    },
    {
      id: "d6",
      siteId: "s-sahyadri",
      date: "2026-08-27",
      weather: "clear",
      workSummary: "Slab 7 pouring 62 cum (south half). Brickwork 3rd floor west 42 sqm.",
      workSummaryMr: "स्लॅब ७ पोरिंग ६२ घनमी (दक्षिण अर्धा). तिसरा मजला पश्चिम विटकाम ४२ चौ.मी.",
      laborCount: 74,
      delays: "None.",
      delaysMr: "नाही.",
      remarks: "Slump 110–120 mm. Cubes cast 6 nos, marked SH-S7-27A.",
      remarksMr: "स्लंप ११०–१२० मिमी. क्यूब्स ६ नग, चिन्ह SH-S7-27A.",
      engineer: "R. Deshpande",
      photos: ["/sites/sahyadri.jpg"],
    },
  ],
  quality: [
    {
      id: "q1",
      siteId: "s-sahyadri",
      date: "2026-08-29",
      title: "Cover check — columns C21–C28",
      titleMr: "कव्हर तपासणी — स्तंभ C21–C28",
      location: "Level 8, grid C",
      result: "pass",
      notes: "40 mm cover maintained. Chairs adequate.",
      inspector: "R. Deshpande",
    },
    {
      id: "q2",
      siteId: "s-sahyadri",
      date: "2026-08-27",
      title: "7-day cube — slab 7 M30",
      titleMr: "७ दिवस क्यूब — स्लॅब ७ M30",
      location: "Lab, Baner",
      result: "hold",
      notes: "Awaiting 7-day crush. 28-day due 24 Sep.",
      inspector: "Lab — Pune Mix",
    },
    {
      id: "q3",
      siteId: "s-godavari",
      date: "2026-08-28",
      title: "Pile verticality P-24",
      titleMr: "पाइल उभ्या दिशा P-24",
      location: "Pier line 3",
      result: "pass",
      notes: "Deviation 0.6%, within 1% spec.",
      inspector: "S. Patil",
    },
    {
      id: "q4",
      siteId: "s-vidya",
      date: "2026-08-29",
      title: "Tile shade and lippage — corridor",
      titleMr: "टाइल शेड आणि लिपेज — कॉरिडॉर",
      location: "Ground floor corridor",
      result: "fail",
      notes: "Lippage > 1 mm on 4 joints. Relaying 12 tiles.",
      inspector: "A. Bhonsle",
    },
  ],
  safety: [
    {
      id: "sf1",
      siteId: "s-sahyadri",
      date: "2026-08-29",
      type: "observation",
      severity: "medium",
      title: "Edge protection missing — slab 8 west",
      titleMr: "एज प्रोटेक्शन नाही — स्लॅब ८ पश्चिम",
      action: "Barricade indented. Work on west edge stopped until fixed.",
      closed: false,
    },
    {
      id: "sf2",
      siteId: "s-godavari",
      date: "2026-08-28",
      type: "near_miss",
      severity: "high",
      title: "Tag line slipped during cage lift",
      titleMr: "केज लिफ्टवेळी टॅग लाइन निसटली",
      action: "Toolbox talk held. Extra rigger posted on boring rig.",
      closed: true,
    },
    {
      id: "sf3",
      siteId: "s-vidya",
      date: "2026-08-26",
      type: "observation",
      severity: "low",
      title: "Painters without goggles in stairwell",
      titleMr: "जिनामध्ये चष्म्याशिवाय रंगारी",
      action: "PPE issued. Supervisor briefed.",
      closed: true,
    },
  ],
  issues: [
    {
      id: "i1",
      siteId: "s-sahyadri",
      date: "2026-08-28",
      title: "Honeycombing at column C4, level 6",
      titleMr: "स्तंभ C4, लेव्हल ६ वर हनीकोम्बिंग",
      location: "Grid C4 / L6",
      severity: "major",
      status: "in_progress",
      assignee: "Kulkarni Constructions",
    },
    {
      id: "i2",
      siteId: "s-godavari",
      date: "2026-08-25",
      title: "32mm TMT mill delay — piers P4–P6",
      titleMr: "३२मिमी TMT मिल उशीर — पियर P4–P6",
      location: "Yard / pier line 2",
      severity: "critical",
      status: "open",
      assignee: "Deshmukh Infra",
    },
    {
      id: "i3",
      siteId: "s-godavari",
      date: "2026-08-20",
      title: "Land acquisition hold on approach A2",
      titleMr: "अप्रोच A2 वर जमीन धारणा",
      location: "Nashik–Peth km 4.2",
      severity: "critical",
      status: "open",
      assignee: "PWD Maharashtra",
    },
    {
      id: "i4",
      siteId: "s-vidya",
      date: "2026-08-29",
      title: "Corridor tile lippage — 12 tiles",
      titleMr: "कॉरिडॉर टाइल लिपेज — १२ टाइल्स",
      location: "GF corridor",
      severity: "minor",
      status: "open",
      assignee: "Joshi Builders",
    },
    {
      id: "i5",
      siteId: "s-sahyadri",
      date: "2026-08-18",
      title: "Basement-2 seepage near lift pit",
      titleMr: "लिफ्ट पिटजवळ बेसमेंट-२ सीपेज",
      location: "B2 lift core",
      severity: "major",
      status: "closed",
      assignee: "Waterproofing subcon",
    },
  ],
};

export function cloneSample(): AppData {
  return structuredClone(SAMPLE);
}
