/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DprRouteImport } from './routes/dpr'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as LaborRouteImport } from './routes/labor'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SitesIndexRouteImport } from './routes/sites.index'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DprRoute = DprRouteImport.update({
  id: '/dpr',
  path: '/dpr',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborRoute = LaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dpr': typeof DprRoute
  '/issues': typeof IssuesRoute
  '/labor': typeof LaborRoute
  '/materials': typeof MaterialsRoute
  '/quality': typeof QualityRoute
  '/safety': typeof SafetyRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dpr': typeof DprRoute
  '/issues': typeof IssuesRoute
  '/labor': typeof LaborRoute
  '/materials': typeof MaterialsRoute
  '/quality': typeof QualityRoute
  '/safety': typeof SafetyRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites': typeof SitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dpr': typeof DprRoute
  '/issues': typeof IssuesRoute
  '/labor': typeof LaborRoute
  '/materials': typeof MaterialsRoute
  '/quality': typeof QualityRoute
  '/safety': typeof SafetyRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dpr'
    | '/issues'
    | '/labor'
    | '/materials'
    | '/quality'
    | '/safety'
    | '/sites/$siteId'
    | '/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dpr'
    | '/issues'
    | '/labor'
    | '/materials'
    | '/quality'
    | '/safety'
    | '/sites/$siteId'
    | '/sites'
  id:
    | '__root__'
    | '/'
    | '/dpr'
    | '/issues'
    | '/labor'
    | '/materials'
    | '/quality'
    | '/safety'
    | '/sites/$siteId'
    | '/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DprRoute: typeof DprRoute
  IssuesRoute: typeof IssuesRoute
  LaborRoute: typeof LaborRoute
  MaterialsRoute: typeof MaterialsRoute
  QualityRoute: typeof QualityRoute
  SafetyRoute: typeof SafetyRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SitesIndexRoute: typeof SitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpr': {
      id: '/dpr'
      path: '/dpr'
      fullPath: '/dpr'
      preLoaderRoute: typeof DprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor': {
      id: '/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof LaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DprRoute: DprRoute,
  IssuesRoute: IssuesRoute,
  LaborRoute: LaborRoute,
  MaterialsRoute: MaterialsRoute,
  QualityRoute: QualityRoute,
  SafetyRoute: SafetyRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  SitesIndexRoute: SitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
